---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alum5368/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp blackpowdercoating.html $DEPLOYPATH
    - /bin/cp choosecolors.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp curtainwall.html $DEPLOYPATH
    - /bin/cp feature.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH
    - /bin/cp -R revolution $DEPLOYPATH
